# Generated by Django 4.0.10 on 2023-04-19 00:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('ci', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='The CI number must be entered in the format: V12345678901. Up to 10 digits allowed.', regex='/^[V|E]\\d{8,10}$/i')])),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: +999999999. Up to 15 digits allowed.', regex='\\+?1?\\d{9,15}$')])),
                ('position', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('sector', models.CharField(choices=[('T', 'Technology'), ('S', 'Services'), ('C', 'Commerce'), ('H', 'Health'), ('E', 'Education'), ('F', 'Food')], default='O', max_length=1)),
                ('rif', models.CharField(max_length=16)),
                ('logo', models.ImageField(help_text='The image MUST NOT have background.', upload_to='logos/')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.contact')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
