# Generated by Django 4.0.10 on 2023-04-19 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_companies_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='contact',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='companies.contact'),
        ),
    ]
