# Generated by Django 4.0.10 on 2023-04-19 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_companies_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companies',
            name='contact',
        ),
        migrations.AddField(
            model_name='contact',
            name='company',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='companies.companies'),
            preserve_default=False,
        ),
    ]
