# Generated by Django 4.0.10 on 2023-04-19 17:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_alter_companies_rif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='rif',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='The RIF number must be entered in the format: J12345678901. Up to 10 digits allowed.', regex='^[JG][-]\\d{8}[-]\\d$')]),
        ),
    ]
