# Generated by Django 4.0.10 on 2023-04-19 17:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_alter_companies_rif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='ci',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='The CI number must be entered in the format: V12345678901. Up to 10 digits allowed.', regex='^[V|E][-]\\d{8}$')]),
        ),
    ]
