# Generated by Django 4.0.10 on 2023-05-14 21:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0012_alter_company_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='rif',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='The RIF number must be entered in the format: J-12345678-1. Up to 8 digits allowed.', regex='^[JG][-]\\d{8}[-]\\d$')]),
        ),
    ]
