# Generated by Django 4.0.10 on 2023-05-16 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_shipping'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('address', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='shipping',
            old_name='address',
            new_name='office',
        ),
    ]
