# Generated by Django 4.0.10 on 2023-08-18 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='card',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='code',
        ),
        migrations.AddField(
            model_name='payment',
            name='browser',
            field=models.CharField(default='str', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='client_ip',
            field=models.GenericIPAddressField(default='192.168.1.1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='dni',
            field=models.CharField(default='V27790607', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='external_id',
            field=models.CharField(default='444555', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='operating_system',
            field=models.CharField(default='Mac OS', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='order_id',
            field=models.UUIDField(default='07d2e9ec-8ffe-4c96-ac91-b97ed6af338f'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='origin_url',
            field=models.URLField(default='https://google.com'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='os_version',
            field=models.CharField(default='1.1', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='request_data',
            field=models.JSONField(default={'data': {}}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='response_data',
            field=models.JSONField(default={'data': {}}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_code',
            field=models.CharField(default='00001', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('A', 'Approved'), ('R', 'Rejected')], default='A', max_length=1),
        ),
    ]
