# Generated by Django 4.0.10 on 2023-08-18 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_rename_external_id_payment_browser_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='response_data',
            field=models.JSONField(null=True),
        ),
    ]
