# Generated by Django 4.0.10 on 2023-03-25 21:34

from django.db import migrations, models
import django.db.models.deletion
import frida_ayala.utils.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('start_date', models.DateField(validators=[frida_ayala.utils.validators.validate_event_time], verbose_name='Show start time')),
                ('end_date', models.DateField(validators=[frida_ayala.utils.validators.validate_event_time], verbose_name='Show end time')),
                ('name', models.CharField(max_length=120, verbose_name='Event name')),
                ('slug_name', models.SlugField(max_length=40, unique=True)),
                ('banner', models.ImageField(unique=True, upload_to='events/banners')),
                ('about', models.CharField(max_length=255, verbose_name='event description')),
                ('type', models.CharField(choices=[('B', 'Banff'), ('S', 'Seminar'), ('O', 'Other')], default='B', max_length=150)),
                ('venue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='venue', to='locations.venue')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='EventDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('date', models.DateField(verbose_name='Show Date')),
                ('start_time', models.TimeField(verbose_name='Show start time')),
                ('end_time', models.TimeField(verbose_name='Show end time')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='show', to='events.event')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('name', models.CharField(max_length=120, verbose_name='Movie name')),
                ('slug_name', models.SlugField(max_length=40, unique=True)),
                ('banner', models.ImageField(unique=True, upload_to='movies/banners')),
                ('duration', models.DurationField()),
                ('about', models.CharField(max_length=255, verbose_name='Movie description')),
                ('trailer_url', models.URLField()),
                ('show', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movie', to='events.eventday')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['slug_name'], name='events_movi_slug_na_719899_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['slug_name'], name='events_even_slug_na_c0aebc_idx'),
        ),
    ]
