# Generated by Django 4.0.10 on 2023-04-19 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_movie_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='show',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movies', to='events.eventday'),
        ),
    ]
