# Generated by Django 4.0.10 on 2023-04-24 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_rename_companies_company'),
        ('events', '0005_itinerary'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sponsors',
            new_name='Sponsor',
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='event_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary', to='events.eventday'),
        ),
    ]
