# Generated by Django 4.0.10 on 2023-05-13 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_rename_sponsors_sponsor_alter_itinerary_event_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='about',
            field=models.TextField(verbose_name='Movie description'),
        ),
    ]
