# Generated by Django 4.0.10 on 2023-05-24 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_movie_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='trailer',
            field=models.URLField(null=True),
        ),
    ]
