# Generated by Django 4.0.10 on 2023-06-01 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_event_trailer'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='main_sponsor',
            field=models.BooleanField(default=True),
        ),
    ]
