# Generated by Django 4.0.10 on 2023-04-13 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tickets',
            field=models.ManyToManyField(through='tickets.OrderTicket', to='tickets.ticket'),
        ),
        migrations.AlterField(
            model_name='orderticket',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.ticket'),
        ),
    ]
