# Generated by Django 4.0.10 on 2023-04-14 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_order_tickets_alter_orderticket_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderticket',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='orderticket',
            name='first_name',
            field=models.CharField(default='ninguno', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderticket',
            name='last_name',
            field=models.CharField(default='ninguno', max_length=16),
            preserve_default=False,
        ),
    ]
