# Generated by Django 4.0.10 on 2023-04-19 01:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_orderticket_active_orderticket_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='entries',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
            preserve_default=False,
        ),
    ]
