# Generated by Django 4.0.10 on 2023-04-19 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_alter_ticket_options_alter_ticket_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderticket',
            name='entries',
            field=models.IntegerField(default=1),
        ),
    ]
