# Generated by Django 4.0.10 on 2023-04-20 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_alter_order_customer_alter_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
    ]
