# Generated by Django 4.0.10 on 2023-04-25 22:58

from django.db import migrations, models
import frida_ayala.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_orderticket_ci_orderticket_qr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketeventday',
            old_name='day',
            new_name='event_day',
        ),
        migrations.AddField(
            model_name='ticketeventday',
            name='stock',
            field=models.IntegerField(default=None, validators=[frida_ayala.utils.validators.validate_ticket_stock]),
            preserve_default=False,
        ),
    ]
