# Generated by Django 4.0.10 on 2023-04-25 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_rename_day_ticketeventday_event_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketeventday',
            name='ticket_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_days', to='tickets.ticket'),
        ),
    ]
