# Generated by Django 4.0.10 on 2023-05-13 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_category_alter_product_supplier_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
