# Generated by Django 4.0.10 on 2023-05-14 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_size_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
