# Generated by Django 4.0.10 on 2023-05-15 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_product_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='size',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.size'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(through='products.CartItem', to='products.size'),
        ),
    ]
