# Generated by Django 4.0.10 on 2023-05-16 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_delivery_rename_address_shipping_office'),
        ('products', '0012_cartitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='locations.delivery'),
        ),
        migrations.AddField(
            model_name='productorder',
            name='payment_method',
            field=models.CharField(choices=[('CARD', 'Debit/Credit card'), ('CASH', 'Cash')], default='CARD', max_length=10),
        ),
        migrations.AddField(
            model_name='productorder',
            name='shipping_method',
            field=models.CharField(choices=[('DELIVERY', 'Delivery'), ('MRW', 'MRW')], default='DELIVERY', max_length=10),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='shipping',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='locations.shipping'),
        ),
    ]
