# Generated by Django 4.0.10 on 2023-05-16 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_productorder_address_productorder_payment_method_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productorder',
            old_name='address',
            new_name='delivery',
        ),
    ]
