# Generated by Django 4.0.10 on 2023-04-20 17:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('ci', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='The CI number must be entered in the format: V12345678901. Up to 10 digits allowed.', regex='^[V|E][-]\\d{8}$')])),
                ('gender', models.CharField(choices=[('F', 'Feminine'), ('M', 'Masculine'), ('O', 'Other')], default='O', max_length=1)),
                ('address', models.CharField(max_length=60)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
