# Generated by Django 4.0.10 on 2023-04-20 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_remove_order_customer'),
        ('users', '0002_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='tickets.order'),
            preserve_default=False,
        ),
    ]
